---
- name: Setup Development Environment
  hosts: localhost
  gather_facts: yes

  tasks:

    - name: Setup APT repositories
      include_tasks: ./apt-repositories_tasks.yml

    - name: Install required packages
      become: yes
      ansible.builtin.apt:
        name:
          - htop
          - curl
          - tree
          - bash-completion
          - make
          - python3-pip
          - zsh
          - tmux
          - git
          - unzip
          - gcc
          - fzf
          - xclip
          - fonts-firacode
          - dotnet-sdk-6.0
          - dotnet-sdk-7.0
        state: present

    - name: Create symbolic links 
      ansible.builtin.file:
        src: "{{ ansible_user_dir }}/.dotfiles/{{ item.src }}"
        dest: "{{ ansible_user_dir }}/{{ item.dest }}"
        state: link
        force: yes
      loop:
        - { src: 'git/.gitconfig', dest: '.gitconfig' }
        - { src: 'zsh/.zshrc', dest: '.zshrc' }
        - { src: 'zsh/.p10k.zsh', dest: '.p10k.zsh' }
        - { src: 'nvim', dest: '.config/nvim' }

    - name: Setup SSH
      include_tasks: ./ssh/ssh_tasks.yml

    - name: Setup ZSH
      include_tasks: ./zsh/zsh_tasks.yml

    - name: Setup Neovim
      include_tasks: ./nvim/nvim_tasks.yml
