---
- name: Setup Development Environment
  hosts: localhost
  gather_facts: yes

  tasks:

    - name: Setup APT repositories
      include_tasks: ./apt-repositories_tasks.yml

    - name: Install required packages
      become: yes
      ansible.builtin.apt:
        name:
          - htop
          - curl
          - tree
          - bash-completion
          - make
          - python3-pip
          - zsh
          - tmux
          - git
          - unzip
          - gcc
          - fzf
          - xclip
          - libfuse2
          - fonts-firacode
          - dotnet-sdk-6.0
          - dotnet-sdk-7.0
          - code
          - alacritty
          - ripgrep
          - snapd
        state: present

    - name: Create symbolic links 
      ansible.builtin.file:
        src: "{{ ansible_user_dir }}/.dotfiles/{{ item.src }}"
        dest: "{{ ansible_user_dir }}/{{ item.dest }}"
        state: link
        force: yes
      loop:
        - { src: 'git/.gitconfig', dest: '.gitconfig' }
        - { src: 'zsh/.zshrc', dest: '.zshrc' }
        - { src: 'zsh/.p10k.zsh', dest: '.p10k.zsh' }
        - { src: 'nvim', dest: '.config/nvim' }
        - { src: 'alacritty/alacritty.yml', dest: '.config/alacritty.yml' }

    - name: Setup ZSH
      include_tasks: ./zsh/zsh_tasks.yml

    - name: Setup Neovim
      include_tasks: ./nvim/nvim_tasks.yml

    - name: Check if fnm install script exists
      ansible.builtin.stat:
        path: "/tmp/install_fnm.sh"
      register: fnm_script_exists
      become: yes

    - name: Download fnm install script
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/Schniz/fnm/master/.ci/install.sh"
        dest: "/tmp/install_fnm.sh"
        mode: "0755"
      when: not fnm_script_exists.stat.exists

    - name: Execute fnm install script
      ansible.builtin.shell: "/tmp/install_fnm.sh"
      become: yes
      when: not fnm_script_exists.stat.exists
