---
- name: Setup .NET Core development environment on WSL
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Install required packages
      become: yes
      ansible.builtin.apt:
        name:
          - htop
          - curl
          - tree
          - bash-completion
          - make
          - python3-pip
          - zsh
          - neovim
          - git
          - unzip
          - gcc
          - fonts-firacode
          - ruby
          - ruby-dev
        state: present

    - name: Decrypt github SSH key
      ansible.builtin.include_vars:
        file: ssh/id_tuliopaim_github.yml
        name: ssh_key_vars

    - name: Copy decrypted github SSH key to ~/.ssh/
      ansible.builtin.copy:
        content: "{{ ssh_key_vars.ssh_private_key }}"
        dest: "{{ ansible_user_dir }}/.ssh-teste/id_tuliopaim_github"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '0600'

    - name: Install and configure ZSH
      block:

        - name: Changing Default Shell to ZSH
          become: yes
          user: 
            name: '{{ ansible_user_id }}'
            shell: /bin/zsh

        - name: Create symbolic links for config files
          ansible.builtin.file:
            src: "{{ ansible_user_dir }}/.dotfiles/{{ item.src }}"
            dest: "{{ ansible_user_dir }}/{{ item.dest }}"
            state: link
            force: yes
          loop:
            - { src: 'zsh/.zshrc', dest: '.zshrc' }

        - name: Check if Oh My Zsh is installed
          ansible.builtin.stat:
            path: "{{ ansible_user_dir }}/.oh-my-zsh"
          register: zsh_folder

        - name: Install Oh My Zsh
          shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" ""
          args:
            creates: "{{ ansible_user_dir }}/oh-my-zsh"
          when: not zsh_folder.stat.exists
        
        - name: Install Powerlevel10k
          git:
            repo: https://github.com/romkatv/powerlevel10k.git
            dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/powerlevel10k"
            clone: yes
            depth: 1
            force: yes
          register: powerlevel10k

        - name: Set Zsh theme to Powerlevel10k
          lineinfile:
            path: "{{ ansible_user_dir }}/.zshrc"
            regexp: '^ZSH_THEME='
            line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'
            state: present
            backup: yes

        - name: Install zsh-autosuggestions
          git:
            repo: https://github.com/zsh-users/zsh-autosuggestions.git
            dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
            clone: yes
            depth: 1
            force: yes

        - name: Add zsh-autosuggestions to plugins list
          lineinfile:
            path: "{{ ansible_user_dir }}/.zshrc"
            regexp: '^plugins='
            line: 'plugins=(zsh-autosuggestions)'
            state: present
            backup: yes

        - name: Set FiraCode NF font in terminal
          lineinfile:
            path: "{{ ansible_user_dir }}/.zshrc"
            regexp: '^export FZF_DEFAULT_OPTS='
            line: 'export FZF_DEFAULT_OPTS="--color=16 --color=fg+:#FF5E7D --color=bg+:#002B36 --color=hl:#B48EAD --color=fg:#839496"'
            state: present
            backup: yes


    - name: Install .NET 6 and 7
      block:
        - name: Check if $HOME/dotnet folder exists
          ansible.builtin.stat:
            path: "{{ ansible_user_dir }}/dotnet"
          register: dotnet_folder

        - name: Create net6 and net7 folders inside $HOME/dotnet
          ansible.builtin.file:
            path: "{{ ansible_user_dir }}/dotnet/{{ item }}"
            state: directory
          with_items:
            - net6
            - net7

        - name: Download .NET Core 6 SDK tarball
          ansible.builtin.get_url:
            url: https://download.visualstudio.microsoft.com/download/pr/868b2f38-62ca-4fd8-93ea-e640cf4d2c5b/1e615b6044c0cf99806b8f6e19c97e03/dotnet-sdk-6.0.407-linux-x64.tar.gz
            dest: /tmp/dotnet-sdk-6.0.407-linux-x64.tar.gz
            checksum: sha512:3cc230f21c0d60ffa4955c01d79cbb41887a41f4e97d0708170e4be8e4dc5bc261269c788c738416c28bbc7e8c6940a89cf3d010f16d1dc4cf25bbb0e2c033c1
            force: no
          when: not dotnet_folder.stat.exists

        - name: Unzip the tarball into $HOME/dotnet
          ansible.builtin.command:
            cmd: tar zxf /tmp/dotnet-sdk-6.0.407-linux-x64.tar.gz -C "{{ ansible_user_dir }}/dotnet/net6"
          when: not dotnet_folder.stat.exists

        - name: Download .NET Core 7 SDK tarball
          ansible.builtin.get_url:
            url: https://download.visualstudio.microsoft.com/download/pr/bda88810-e1a6-4cf0-8139-7fd7fe7b2c7a/7a9ffa3e12e5f1c3d8b640e326c1eb14/dotnet-sdk-7.0.202-linux-x64.tar.gz
            dest: /tmp/dotnet-sdk-7.0.202-linux-x64.tar.gz
            checksum: sha512:f415a8e6c078421759a963aa0b232c092ecf2f0a8e014ba72092390aac792ed35e8f3c822b2ce91ed636cdee9342bba2b89fb4fdfd2d28dbb0ac856d828cb29f
            force: no
          when: not dotnet_folder.stat.exists

        - name: Unzip the tarball into $HOME/dotnet
          ansible.builtin.command:
            cmd: tar zxf /tmp/dotnet-sdk-7.0.202-linux-x64.tar.gz -C "{{ ansible_user_dir }}/dotnet/net7"
          when: not dotnet_folder.stat.exists


