---
- name: Setup Development Environment
  hosts: localhost
  gather_facts: yes

  tasks:

    - name: Install Microsoft apt repository key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present
      become: yes

    - name: Add Microsoft apt repository
      apt_repository:
        repo: 
          'deb [arch=amd64]
          https://packages.microsoft.com/{{ ansible_lsb.id | lower }}/{{ ansible_distribution_version }}/prod
          {{ ansible_distribution_release }}
          main'
        state: present
        filename: 'packages-microsoft-prod.list'
        mode: '0644'
        update_cache: yes
      become: yes

    - name: Install required packages
      become: yes
      ansible.builtin.apt:
        name:
          - htop
          - curl
          - tree
          - bash-completion
          - make
          - python3-pip
          - zsh
          - neovim
          - git
          - unzip
          - gcc
          - fzf
          - fonts-firacode
          - dotnet-sdk-6.0
          - dotnet-sdk-7.0
        state: present


    - name: Copy Github SSH key
      block:
      - name: Ensure the SSH folder exists
        ansible.builtin.file:
          path: "{{ ansible_user_dir }}/.ssh/"
          state: directory

      - name: Decrypt github SSH key
        ansible.builtin.include_vars:
          file: ssh/id_tuliopaim_github.yml
          name: ssh_key_vars

      - name: Copy decrypted github SSH key to ~/.ssh/
        ansible.builtin.copy:
          content: "{{ ssh_key_vars.ssh_private_key }}"
          dest: "{{ ansible_user_dir }}/.ssh/id_tuliopaim_github"
          owner: "{{ ansible_user_id }}"
          group: "{{ ansible_user_id }}"
          mode: '0600'

      - name: Copy public github SSH key 
        ansible.builtin.copy:
          content: "{{ ansible_user_dir }}/.dotfiles/ssh/id_tuliopaim_github.pub"
          dest: "{{ ansible_user_dir }}/.ssh/id_tuliopaim_github.pub"
          owner: "{{ ansible_user_id }}"
          group: "{{ ansible_user_id }}"
          mode: '0600'

    - name: Create symbolic links for .gitconfig
      ansible.builtin.file:
        src: "{{ ansible_user_dir }}/.dotfiles/{{ item.src }}"
        dest: "{{ ansible_user_dir }}/{{ item.dest }}"
        state: link
        force: yes
      loop:
        - { src: 'git/.gitconfig', dest: '.gitconfig' }

    - name: Install and configure ZSH
      block:

        - name: Changing Default Shell to ZSH
          become: yes
          user: 
            name: '{{ ansible_user_id }}'
            shell: /bin/zsh

        - name: Create symbolic links for config files
          ansible.builtin.file:
            src: "{{ ansible_user_dir }}/.dotfiles/{{ item.src }}"
            dest: "{{ ansible_user_dir }}/{{ item.dest }}"
            state: link
            force: yes
          loop:
            - { src: 'zsh/.zshrc', dest: '.zshrc' }
            - { src: 'zsh/.p10k.zsh', dest: '.p10k.zsh' }

        - name: Check if Oh My Zsh is installed
          ansible.builtin.stat:
            path: "{{ ansible_user_dir }}/.oh-my-zsh"
          register: zsh_folder

        - name: Install Oh My Zsh
          shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" ""
          args:
            creates: "{{ ansible_user_dir }}/oh-my-zsh"
          when: not zsh_folder.stat.exists
        
        - name: Install Powerlevel10k
          git:
            repo: https://github.com/romkatv/powerlevel10k.git
            dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/powerlevel10k"
            clone: yes
            depth: 1
            force: yes
          register: powerlevel10k

        - name: Set Zsh theme to Powerlevel10k
          lineinfile:
            path: "{{ ansible_user_dir }}/.zshrc"
            regexp: '^ZSH_THEME='
            line: 'ZSH_THEME="powerlevel10k/powerlevel10k"'
            state: present
            backup: yes

        - name: Install zsh-autosuggestions
          git:
            repo: https://github.com/zsh-users/zsh-autosuggestions.git
            dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
            clone: yes
            depth: 1
            force: yes

        - name: Add zsh-autosuggestions to plugins list
          lineinfile:
            path: "{{ ansible_user_dir }}/.zshrc"
            regexp: '^plugins='
            line: 'plugins=(zsh-autosuggestions)'
            state: present
            backup: yes

        - name: Set FiraCode NF font in terminal
          lineinfile:
            path: "{{ ansible_user_dir }}/.zshrc"
            regexp: '^export FZF_DEFAULT_OPTS='
            line: 'export FZF_DEFAULT_OPTS="--color=16 --color=fg+:#FF5E7D --color=bg+:#002B36 --color=hl:#B48EAD --color=fg:#839496"'
            state: present
            backup: yes
