---
- name: Install and configure neovim
  block:

    - name: Check if Neovim AppImage is downloaded
      stat:
        path: "{{ ansible_user_dir }}/nvim.appimage"
      register: nvim_appimage
        
    - name: Download and install Neovim stable via AppImage
      become: yes
      get_url:
        url: https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
        dest: "{{ ansible_user_dir }}"
        mode: 0755
      when: not nvim_appimage.stat.exists

    - name: Check if Neovim is extracted
      stat:
        path: "{{ ansible_user_dir }}/squashfs-root"
      register: nvim_extracted

    - name: Extract Neovim stable from AppImage
      command: "{{ ansible_user_dir }}/nvim.appimage --appimage-extract"
      become: yes
      args:
        chdir: "{{ ansible_user_dir }}"
      when: not nvim_extracted.stat.exists

    - name: Move Neovim stable
      ansible.builtin.shell: "mv {{ ansible_user_dir }}/squashfs-root /opt/nvim"
      become: yes
      args:
        creates: /opt/nvim

    - name: Check if Neovim symlink exists
      stat:
        path: /usr/local/bin/nvim
      register: nvim_symlink

    - name: Create symlink for Neovim stable
      become: yes
      ansible.builtin.file:
        src: /opt/nvim-stable/usr/bin/nvim
        dest: /usr/local/bin/nvim
        state: link
        force: yes
      when: not nvim_symlink.stat.exists

    - name: Check if packer.nvim is cloned
      stat:
        path: "{{ ansible_user_dir }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
      register: packer_nvim

    - name: Clone packer.nvim
      git:
        repo: https://github.com/wbthomason/packer.nvim
        dest: "{{ ansible_user_dir }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
        depth: 1
      when: not packer_nvim.stat.exists
