#include QMK_KEYBOARD_H
#include <stdio.h>

// Each layer gets a name for readability. These should be in sequential order.
#define _BASE 0
#define _FN1 1
#define _FN2 2
#define _FN3 3

// Defines for layer movement and readability
#define _______ KC_TRNS
#define XXXXXXX KC_NO

// Special characters
#define CEDILHA ç

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

/* BASE
/* ,-----------------------------------------.                    ,-----------------------------------------.
 * | ESC  |  1   |  2   |  3   |  4   |  5   |                    |  6   |  7   |  8   |  9   |  0   | GRV  |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * | TAB  |  Q   |  W   |  E   |  R   |  T   |                    |  Y   |  U   |  I   |  O   |  P   | MINS |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * | LSFT |  A   |  S   |  D   |  F   |  G   |                    |  H   |  J   |  K   |  L   | SCLN | QUOT |
 * |------+------+------+------+------+------|-------.    ,-------|------+------+------+------+------+------|
 * | LCTL |  Z   |  X   |  C   |  V   |  B   | LBRC  |    | BSPC  |  N   |  M   | COMM | DOT  | SLSH | ENT  |
 * `------+------+------+------+------+------|-------/    \-------|------+------+------+------+------+------|
 *                   | LALT | LGUI |MO(1) | / SPC   /      \ ENT   \  |MO(2) | LALT | PSCR |
 *                   |      |      |      |/       /        \       \ |      |      |      |
 *                   `----------------------------'          '-------''--------------------'
 *                                                                               generated by [keymapviz] */

     */
    [_BASE] = LAYOUT(
      KC_ESC,   KC_1,    KC_2,    KC_3,    KC_4,    KC_5,                      KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_GRV,
      KC_TAB,   KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,                      KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_MINS,
      KC_LSFT,  KC_A,    KC_S,    KC_D,    KC_F,    KC_G,                      KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,
      KC_LCTL,  KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,   KC_LBRC, KC_BSPC,  KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_ENT,
                                    KC_LALT, KC_LGUI, MO(1),  KC_SPC,  KC_ENT,  MO(2),  KC_LALT, KC_PSCR
    ),

/* FN1 - for F keys, navigation, etc.
/* ,-----------------------------------------.                    ,-----------------------------------------.
 * |      |  F1  |  F2  |  F3  |  F4  |  F5  |                    |  F6  |  F7  |  F8  |  F9  |      |RALT(K|
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * | CAPS |OSM(MO|  UP  |RALT(K|RALT(K|      |                    | F10  | F11  | F12  | LBRC | RBRC | EQL  |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      | LEFT | DOWN | RGHT | LPRN | RPRN |                    | LEFT | DOWN |  UP  | RGHT | BSPC |RALT(K|
 * |------+------+------+------+------+------|-------.    ,-------|------+------+------+------+------+------|
 * |      |      |      |      | LCBR | RCBR |       |    | DEL   | HOME | PGDN | PGUP | END  | BSLS |      |
 * `------+------+------+------+------+------|-------/    \-------|------+------+------+------+------+------|
 *                   |      |      |TG(0) | /       /      \       \  |MO(3) |      |      |
 *                   |      |      |      |/       /        \       \ |      |      |      |
 *                   `----------------------------'          '-------''--------------------'
 *                                                                               generated by [keymapviz] */

    [_FN1] = LAYOUT(
      _______, KC_F1,         KC_F2,   KC_F3,         KC_F4,         KC_F5,                     KC_F6,   KC_F7,   KC_F8,   KC_F9,   _______, RALT(KC_TILD),
      KC_CAPS, OSM(MOD_MEH),  KC_UP,   RALT(KC_TILD), RALT(KC_CIRC), _______,                   KC_F10,  KC_F11,  KC_F12,  KC_LBRC, KC_RBRC, KC_EQL,
      _______, KC_LEFT,       KC_DOWN, KC_RGHT,       KC_LPRN,       KC_RPRN,                   KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT, KC_BSPC, RALT(KC_QUOT),
      _______, _______,       _______, _______,       KC_LCBR,       KC_RCBR, _______, KC_DEL,  KC_HOME, KC_PGDN, KC_PGUP, KC_END,  KC_BSLS, _______,
                                 _______, _______,  TG(0) , _______,                       _______,  MO(3)  , _______, _______
    ),

/* FN2 - Mouse and Media
/* ,-----------------------------------------.                    ,-----------------------------------------.
 * |      |      |      |      |      |      |                    |      |      |      |      |      |QK_BOO|
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |      |      |      | MPRV | MNXT |                    | BTN1 | BTN2 |      |      |      |QK_CLE|
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |      |      |      |      | MPLY | MSTP |                    | WH_L | WH_D | WH_U | WH_R |      |      |
 * |------+------+------+------+------+------|-------.    ,-------|------+------+------+------+------+------|
 * |      |      |      | MUTE | VOLD | VOLU |       |    |       | MS_L | MS_D | MS_U | MS_R |      |      |
 * `------+------+------+------+------+------|-------/    \-------|------+------+------+------+------+------|
 *                   |      |      |TG(0) | /       /      \       \  |      |      |      |
 *                   |      |      |      |/       /        \       \ |      |      |      |
 *                   `----------------------------'          '-------''--------------------'
 *                                                                               generated by [keymapviz] */
    [_FN2] = LAYOUT(
      _______, _______, _______, _______, _______, _______,                     _______, _______, _______, _______, _______, QK_BOOT,
      _______, _______, _______, _______, KC_MPRV, KC_MNXT,                     KC_BTN1, KC_BTN2, _______, _______, _______, QK_CLEAR_EEPROM,
      _______, _______, _______, _______, KC_MPLY, KC_MSTP,                     KC_WH_L, KC_WH_D, KC_WH_U, KC_WH_R, _______, _______,
      _______, _______, _______, KC_MUTE, KC_VOLD, KC_VOLU, _______,  _______,  KC_MS_L, KC_MS_D, KC_MS_U, KC_MS_R, _______, _______,
                                 _______, _______, TG(0),   _______,  _______,  _______, _______, _______
    ),
};

