#!/usr/bin/env bash

exec swayidle -w \
    timeout 1000 'swaylock -f -c 000000' \
    timeout 1500 'hyprctl dispatch dpms off' \
    resume 'hyprctl dispatch dpms on' \
    before-sleep 'swaylock -f -c 000000'
