# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
$terminal = uwsm app -- $TERMINAL
$browser = omarchy-launch-browser

unbind = SUPER, W
unbind = SUPER, K
unbind = SUPER, J
unbind = SUPER, L
unbind = SUPER, S

bindd = SUPER, Q, Close window, killactive,

bindd = SUPER SHIFT, S, Toggle split, layoutmsg, togglesplit
bindd = SUPER SHIFT, Q, Close active window, killactive,
bindd = SUPER, RETURN, Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, $browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, $browser --private
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, T, Activity, exec, omarchy-launch-tui btop
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus obsidian "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER, SEMICOLON , Clipboard, exec, omarchy-launch-walker -m clipboard

# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
bindd = SUPER SHIFT, X, X, exec, omarchy-launch-webapp "https://x.com/"
bindd = SUPER SHIFT ALT, X, X Post, exec, omarchy-launch-webapp "https://x.com/compose"

# Move focus with mainMod + vim motions
bind = SUPER, h, movefocus, l
bind = SUPER, l, movefocus, r
bind = SUPER, k, movefocus, u
bind = SUPER, j, movefocus, d

# Move window
bind = SUPER_SHIFT, h, movewindow, l
bind = SUPER_SHIFT, l, movewindow, r
bind = SUPER_SHIFT, k, movewindow, u
bind = SUPER_SHIFT, j, movewindow, d

# Screenshots (unbind Print key defaults, remap to ALT+SHIFT)
unbind = , Print
unbind = ALT, Print
bindd = ALT SHIFT, 1, Full screenshot, exec, omarchy-cmd-screenshot fullscreen
bindd = ALT SHIFT, 2, Region screenshot, exec, omarchy-cmd-screenshot region

# Resize window
bind = SUPER_ALT, l, resizeactive, 20 0
bind = SUPER_ALT, h, resizeactive, -20 0
bind = SUPER_ALT, k, resizeactive, 0 -20
bind = SUPER_ALT, j, resizeactive, 0 20

# Toggle between scrolling and dwindle layout on current workspace
bindd = SUPER, BACKSLASH, Toggle workspace layout, exec, omarchy-hyprland-workspace-layout-toggle
