# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows
    # gaps_in = 0
    # gaps_out = 0

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#scrolling
# Set workspace 2 to scrolling layout by default
workspace = 2, layout:scrolling

# https://wiki.hyprland.org/Configuring/Variables/#scrolling
scrolling {
    column_width = 0.5
    focus_fit_method = 1
    fullscreen_on_one_column = true
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}
