---
- name: Ensure the script is present and executable
  become: yes
  copy: 
    src: ./create_symlinks.sh
    dest: ./create_symlinks.sh
    mode: '0755'
  tags: ['symbolic', 'links']
    
- name: Run the script
  become: yes
  shell: ./create_symlinks.sh
  tags: ['symbolic', 'links']
