---
- name: Add Docker GPG apt Key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  become: yes
  apt: 
    name: 
      - docker-ce
    state: latest

- name: Add users do docker group
  become: yes
  shell: usermod -aG docker tuliopaim &&  usermod -aG docker p1  && usermod -aG docker p2
