---
- name: Check if dotnet-install.sh is already downloaded
  ansible.builtin.stat:
    path: /tmp/dotnet/dotnet-install.sh
  register: dotnet_install_script
  tags: ['dotnet']

- name: Create directory for dotnet-install.sh
  ansible.builtin.file:
    path: /tmp/dotnet/
    state: directory
    mode: '0755'
  when: not dotnet_install_script.stat.exists
  tags: ['dotnet']

- name: Download dotnet-install.sh script
  ansible.builtin.get_url:
    url: https://dot.net/v1/dotnet-install.sh
    dest: /tmp/dotnet/dotnet-install.sh
    mode: '0755'
  when: not dotnet_install_script.stat.exists
  tags: ['dotnet']

- name: Execute dotnet-install.sh for channel 6.0
  become: yes
  become_user: "{{ item }}"
  ansible.builtin.shell: /tmp/dotnet/dotnet-install.sh --channel 6.0
  when: not dotnet_install_script.stat.exists
  loop: "{{ users }}"
  tags: ['dotnet']

- name: Execute dotnet-install.sh for channel 7.0
  become: yes
  become_user: "{{ item }}"
  ansible.builtin.shell: /tmp/dotnet/dotnet-install.sh --channel 7.0
  when: not dotnet_install_script.stat.exists
  loop: "{{ users }}"
  tags: ['dotnet']
