---
- name: Install and configure ZSH
  block:

    - name: Install dnf-plugins-core
      become: yes
      command: dnf install dnf-plugins-core
      tags: ['packages']

    - name: Add Docker repository
      become: yes
      command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
      tags: ['packages']

    - name: Install required packages
      become: yes
      ansible.builtin.dnf:
        name:
          - htop
          - curl
          - tree
          - bash-completion
          - make
          - pip
          - zsh
          - tmux
          - git
          - unzip
          - gcc
          - gcc-c++
          - fzf
          - fd-find
          - xclip
          - alacritty
          - ripgrep
          - snapd
          - flameshot
          - copyq
          - bat
          - obs-studio
          - docker-ce
          - docker-ce-cli
          - containerd.io 
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
      tags: ['packages']

    - name: Install FNM
      shell: curl -fsSL https://fnm.vercel.app/install | bash
      tags: ['packages']

    - name: Install Node
      command: fnm install 20.11
      tags: ['packages']

