---
- name: Add Docker GPG apt Key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: ['docker']

- name: Add Docker Repository
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present
  tags: ['docker']

- name: Update apt and install docker-ce
  become: yes
  apt: 
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - docker-compose
    state: latest
  tags: ['docker']

- name: Add users do docker group
  become: yes
  shell: usermod -aG docker tuliopaim &&  usermod -aG docker p1  && usermod -aG docker p2
  tags: ['docker']
