---
- name: Install and configure ZSH
  block:
    - name: Changing Default Shell to ZSH for all users
      become: yes
      user:
        name: "tuliopaim"
        shell: /usr/bin/zsh

    - name: Check if Oh My Zsh is installed
      ansible.builtin.stat:
        path: "{{ home }}/.oh-my-zsh"
      register: zsh_folder

    - name: Install Oh My Zsh
      become: yes
      shell: >
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        creates: "{{ home }}/.oh-my-zsh"
      environment:
        ZSH: "{{ home }}/.oh-my-zsh"
      when: not zsh_folder.stat.exists

    - name: Check if zsh-autosuggestions is installed
      ansible.builtin.stat:
        path: "{{ home }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
      register: zsh_autosuggestions_folder

    - name: Install zsh-autosuggestions
      become: yes
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: "{{ home }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
        clone: yes
        depth: 1
        force: yes
      when: not zsh_autosuggestions_folder.stat.exists
