---
- name: Check if fnm install script exists
  ansible.builtin.stat:
    path: "/home/tuliopaim/.local/share/fnm"
  register: fnm_exists
  become: yes
  tags: ['fnm', 'node']

- name: Install fnm if not installed
  shell: curl -fsSL https://fnm.vercel.app/install | bash -s -- --install-dir "{{ share }}/.fnm" --skip-shell
  when: not fnm_exists.stat.exists
  tags: ['fnm', 'node']

- name: Install Node.js versions
  shell: fnm install {{ item }}
  loop:
    - 16.16
    - 18.17
  when: not fnm_exists.stat.exists
  tags: ['fnm', 'node']
