- name: Install packages
  include_tasks: install_packages.yml
  tags: ['packages']

- name: Install and configure ZSH
  block:
    - name: Install common packages
      block:
        - name: Install dnf-plugins-core
          become: yes
          command: dnf install -y dnf-plugins-core
          tags: ['packages']
          
        - name: Install required packages (Fedora)
          become: yes
          ansible.builtin.dnf:
            name:
              - htop
              - curl
              - tree
              - bash-completion
              - make
              - pip
              - zsh
              - tmux
              - git
              - unzip
              - gcc
              - gcc-c++
              - fzf
              - fd-find
              - xclip
              - alacritty
              - ripgrep
              - snapd
              - flameshot
              - copyq
              - bat
              - obs-studio
              - docker-ce
              - docker-ce-cli
              - containerd.io 
              - docker-buildx-plugin
              - docker-compose-plugin
            state: present
          when: ansible_distribution == 'Fedora'
          tags: ['packages']

        - name: Install FNM and Node (Fedora)
          shell: |
            curl -fsSL https://fnm.vercel.app/install | bash
            fnm install 20.11
          when: ansible_distribution == 'Fedora'
          tags: ['packages']
      when: ansible_distribution == 'Fedora'

    - name: Install required packages (Arch)
      become: yes
      pacman:
        name:
          - htop
          - curl
          - tree
          - bash-completion
          - make
          - python-pip
          - zsh
          - tmux
          - git
          - unzip
          - gcc
          - fzf
          - fd
          - xclip
          - alacritty
          - ripgrep
          - snapd
          - flameshot
          - copyq
          - bat
          - obs-studio
          - docker
      tags: ['packages']
      when: ansible_distribution == 'Arch'

    - name: Install FNM and Node (Arch)
      become: yes
      shell: |
        curl -fsSL https://fnm.vercel.app/install | bash
        fnm install 20.11
      tags: ['packages']
      when: ansible_distribution == 'Arch'
