---
- name: Simplified Neovim installation
  hosts: all
  become: yes  # Using 'become: yes' at the play level to apply it for all tasks that require sudo.
  vars:
    neovim_url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage

  tasks:
    - name: Download Neovim AppImage
      get_url:
        url: "{{ neovim_url }}"
        dest: "{{ home }}/nvim.appimage"  # Downloads directly to the user's home directory.
        mode: '0755'
      register: download_task
      become: no  # Download as the user, not root.

    - name: Extract Neovim AppImage
      command: "./nvim.appimage --appimage-extract"
      args:
        chdir: "{{ home }}"
      when: download_task.changed
      become: no  # Extract as the user, not root.

    - name: Move extracted directory to root
      command: "mv {{ home }}/squashfs-root /"
      when: download_task.changed

    - name: Create symlink for Neovim
      file:
        src: "/squashfs-root/AppRun"
        dest: "/usr/bin/nvim"
        state: link
      when: download_task.changed

