---
- name: Ensure the script is present and executable
  become: yes
  copy: 
    src: ./install_firacode.sh
    dest: ./install_firacode.sh
    mode: '0755'
  tags: ['firacode']
    
- name: Run the script
  become: yes
  shell: ./install_firacode.sh
  tags: ['firacode']
