---
- name: Install and configure ZSH
  block:
    - name: Install required packages
      become: yes
      ansible.builtin.dnf:
        name:
          - htop
          - curl
          - tree
          - bash-completion
          - make
          - python3-pip
          - zsh
          - tmux
          - git
          - unzip
          - gcc
          - fzf
          - fd-find
          - xclip
          - libfuse2
          - code
          - alacritty
          - ripgrep
          - snapd
          - aptitude
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - flameshot
          - copyq
          - bat
        state: present
        tags: ['packages']

    - name: Install bat
      block:

        - name: Create symlink from fdfind to fd
          become: yes
          file:
            src: /usr/bin/fdfind
            dest: /usr/bin/fd
            state: link
          tags: ['packages']
