---
- name: Setup Development Environment
  hosts: localhost
  gather_facts: yes
  vars:
    users:
      - 'tuliopaim'
      - 'p1'

    dotfiles: "{{ share }}/.dotfiles"
    share: "/usr/local/share"

  tasks:
    - name: Install packages
      include_tasks: install_packages.yml
      tags: ['packages']

    - name: Set necessary permissions on shared folders
      become: yes
      file:
        path: "{{ item }}"
        owner: 'tuliopaim'
        group: 'tuliopaim'
        mode: '0775'
        recurse: yes  
      loop: "{{ links }}"
      vars:
        links:
          - "{{ share }}"
          - "{{ dotfiles }}"
      tags: ['zsh', 'tmux', 'nvim', 'symbolic-links', 'permissions']

    - name: Setup Oh My Zsh
      include_tasks: install_oh_my_zsh.yml
      tags: ['zsh']

    - name: Install firacode
      block:
      - name: Ensure the script is present and executable
        become: yes
        copy: 
          src: ./install_firacode.sh
          dest: ./install_firacode.sh
          mode: '0755'
        tags: ['firacode']
          
      - name: Run the script
        become: yes
        shell: ./install_firacode.sh
        tags: ['firacode']

    - name: Setup Neovim
      include_tasks: install_nvim.yml
      tags: ['nvim']

    - name: Setup tmux TPM
      block:
      - name: Check if tmux tpm is installed
        stat:
          path: "{{ share }}/.tmux/plugins/tpm"
        register: tmux
        tags: ['tmux']

      - name: Clone tmux tpm
        git:
          repo: https://github.com/tmux-plugins/tpm
          dest: "{{ share }}/.tmux/plugins/tpm"  
          depth: 1
        when: not tmux.stat.exists
        tags: ['tmux']

    - name: Create symbolic links for all users
      include_tasks: create_symlinks.yml
      tags: ['symbolic-links', 'permissions']

    - name: Setup dotnet
      include_tasks: install_dotnet.yml
      tags: 
        - dotnet
        - dotnet6 
        - dotnet7
        - dotnet8

    - name: Setup docker
      include_tasks: install_docker.yml
      tags: ['docker']
        
