---
- name: Setup Development Environment
  hosts: localhost
  gather_facts: yes
  vars:
    home: "/home/tuliopaim"
    dotfiles: "{{ home }}/.dotfiles"

  tasks:
    - name: Install packages
      include_tasks: install_packages.yml
      tags: ['packages']

    - name: Setup Oh My Zsh
      include_tasks: install_oh_my_zsh.yml
      tags: ['zsh']

    - name: Install firacode
      block:
      - name: Ensure the script is present and executable
        become: yes
        copy: 
          src: ./install_firacode.sh
          dest: ./install_firacode.sh
          mode: '0755'
        tags: ['firacode']
          
      - name: Run the script
        become: yes
        shell: ./install_firacode.sh
        tags: ['firacode']

    - name: Setup tmux TPM
      block:
      - name: Check if tmux tpm is installed
        stat:
          path: "{{ home }}/.tmux/plugins/tpm"
        register: tmux
        tags: ['tmux']

      - name: Clone tmux tpm
        git:
          repo: https://github.com/tmux-plugins/tpm
          dest: "{{ home }}/.tmux/plugins/tpm"  
          depth: 1
        when: not tmux.stat.exists
        tags: ['tmux']

    - name: Ensure symlinks.sh is present and executable
      become: no
      ansible.builtin.file:
        path: "{{ home }}/.dotfiles/symlinks.sh"
        mode: '0755'
      tags: [ 'symlinks' ]

    - name: Execute symlinks.sh
      become: no
      command: "{{ home }}/.dotfiles/symlinks.sh"
      tags: [ 'symlinks' ]

    - name: Setup dotnet
      include_tasks: install_dotnet.yml
      tags: 
        - dotnet
        - dotnet6 
        - dotnet7
        - dotnet8

