---
- name: Setup Development Environment
  hosts: localhost
  gather_facts: yes
  vars:
    users:
      - 'tuliopaim'
      - 'p1'
      - 'p2'

    dotfiles: "{{ share }}/.dotfiles"
    share: "/usr/local/share"

  tasks:
    - name: Install packages
      include_tasks: install_packages.yml
      tags: ['packages']

    - name: Set necessary permissions on shared folders
      become: yes
      file:
        path: "{{ item }}"
        owner: 'root'
        group: 'developer'
        mode: '0775'
        recurse: yes  
      loop: "{{ links }}"
      vars:
        links:
          - "{{ share }}"
          - "{{ dotfiles }}"
      tags: ['zsh', 'symbolic-links', 'permissions']

    - name: Setup Oh My Zsh
      include_tasks: install_oh_my_zsh.yml
      tags: ['zsh']

    - name: Setup firacode
      include_tasks: install_firacode.yml
      tags: ['firacode']

    - name: Setup Neovim
      include_tasks: install_nvim.yml
      tags: ['nvim']

    - name: Setup tmux
      include_tasks: install_tmux.yml
      tags: ['tmux']

    - name: Create symbolic links for all users
      include_tasks: create_symlinks.yml
      tags: ['symbolic-links', 'permissions']

    - name: Setup dotnet
      include_tasks: install_dotnet.yml
      tags: 
        - dotnet
        - dotnet6 
        - dotnet7
        - dotnet8

    - name: Setup docker
      include_tasks: install_docker.yml
      tags: ['docker']
        
    - name: Fix cedilha
      include_tasks: fix_cedilha_popos.yml
      tags: ['cedilha']

    - name: Set Neovim as default Git editor for each user
      become: yes
      become_user: "{{ item }}"
      ansible.builtin.shell:
        cmd: git config --global core.editor "nvim"
      loop: "{{ users }}"
